In [3]:
# !pip install pycaret

In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import imblearn
import pickle
from pycaret.classification import *
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from utils import *

%matplotlib inline

In [5]:
# GLOBAL VAR
PATH = './'

In [6]:
df = pd.read_csv(PATH+'data_testing.csv')
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,90000,2,2.0,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
1,100000,2,2.0,2,23,0,-1,-1,0,0,...,221.0,-159.0,567.0,380.0,601.0,0.0,581.0,1687.0,1542.0,0
2,20000,1,1.0,2,24,0,0,2,2,2,...,18338.0,17905.0,19104.0,3200.0,0.0,1500.0,0.0,1650.0,0.0,1
3,180000,2,1.0,2,29,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,130000,2,3.0,2,39,0,0,0,0,0,...,20616.0,11802.0,930.0,3000.0,1537.0,1000.0,2000.0,930.0,33764.0,0

In [7]:
# Load custom pipeline
filename = PATH+'cust_pipe.pkl'
with open(filename, "rb") as f:
    cust_pipeline = pickle.load(f)

In [9]:
# Load pycaret pipeline
# load_config(PATH+'pycaret_pipe')

In [10]:
# Load model
saved_final_lr = load_model(PATH+'model_LR')

Transformation Pipeline and Model Successfully Loaded

In [11]:
# Custom transformations
df_new = cust_pipeline.transform(df)

---- GenerateMissingIndicator transform method ----
---- GroupRareLevels transform method ----
---- OutlierRemovalIQR transform method ----

In [12]:
df_pred = predict_model(saved_final_lr, data=df_new)
df_pred.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,EDUCATION_missing,default,prediction_label,prediction_score
0,90000,2,2.0,2,34,0,0,0,0,0,...,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0,0,0,0.5327
1,100000,2,2.0,2,23,0,-1,-1,0,0,...,380.0,601.0,0.0,581.0,1687.0,1542.0,0,0,0,0.5794
2,20000,1,1.0,2,24,0,0,2,2,2,...,3200.0,0.0,1500.0,0.0,1650.0,0.0,0,1,1,0.5979
3,180000,2,1.0,2,29,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1,0.5182
4,130000,2,3.0,2,39,0,0,0,0,0,...,3000.0,1537.0,1000.0,2000.0,930.0,33764.0,0,0,0,0.5449

In [13]:
df_pred.to_csv(PATH+'pred_testing.csv')